### ISSUE TITLE
Missing SQL store support

### ISSUE THREAD

**Issue by deltasquare4** [temporalio/helm-charts#121]
I have been trying to deploy Temporal.io with MySQL store support. I see the rest of the chart is heavily inspired from [banzaicloud's cadence chart](https://github.com/banzaicloud/banzai-charts/tree/master/cadence), but it seems MySQL support has been explicitly removed from the chart while Temporal itself seems to support it.

Is there a specific reason?

I have made changes to this chart to support it for my use for now. If the Temporal team/community is interested, I can create a PR.

**Comment by underrun** [comment]
we should support mysql via the helm chart - see the relevant values file for an example:

https://github.com/temporalio/helm-charts/blob/master/values/values.mysql.yaml

if this isn't working, please let us know
