### ISSUE TITLE
ElasticSearch password should be in a secret not the configmap

### ISSUE THREAD

**Issue by robholland** [temporalio/helm-charts#144]
As with persistence passwords ElasticSearch password should be in a secret.

**Comment by SmaineTF1** [comment]
Is there any news with this issue? Actually that's a real problem, for example in a GitOps workflow we'll have to commit the password :/

**Comment by LukaGiorgadze** [comment]
You can use Terraform [helm_provider](https://registry.terraform.io/providers/hashicorp/helm/latest/docs) and pass any sensitive data dynamically + your helm will stay unchanged and you can keep it up to date without merging troubles.

**Comment by robholland** [comment]
Fixed by https://github.com/temporalio/helm-charts/pull/522
