### ISSUE TITLE
SchemaUpdate: Kube spec only supports cassandra for schema update job

### ISSUE THREAD

**Issue by thempatel** [temporalio/helm-charts#151]
As the title says, the schema update job rendering is broken, as-is if a user is not using cassandra, then the update job will attempt to start the _temporal server_ since the container receives no args.

https://github.com/temporalio/helm-charts/blob/ca48bfe7e9c1619ac2f2a3a72ca8c991c8922054/templates/server-job.yaml#L168-L171

versus:

https://github.com/temporalio/helm-charts/blob/ca48bfe7e9c1619ac2f2a3a72ca8c991c8922054/templates/server-job.yaml#L86

**Comment by sw-yx** [comment]
other users have documented non-cassandra modifications for now, see https://github.com/temporalio/helm-charts/issues?q=sort%3Aupdated-desc+label%3AAlternative+is%3Aclosed
