### ISSUE TITLE
Make sure logger is configured correctly by default

### ISSUE THREAD

**Issue by samarabbas** [temporalio/helm-charts#153]
If the config for server is missing `log` section then server sets the output stream as `stderr`.
Users need to explicitly configure logger by providing the following section in config:
```
log:
  stdout: true
  level: info
```

Relevant [code](https://github.com/temporalio/temporal/blob/3d10123811f2fc040664fb8e8bcf530ddbed062a/common/log/zap_logger.go#L185) which sets the logger.

**Comment by underrun** [comment]
closing as we have decided that `stderr` is the correct default stream for logs as it ends up in pod logs and has the advantage of being unbuffered.

this remains configurable for those who would prefer to log to stdout or change the log level.
