### ISSUE TITLE
Admintools has an invalid TEMPORAL_CLI_ADDRESS when deployed in a non-default namespace

### ISSUE THREAD

**Issue by iamjohnnym** [temporalio/helm-charts#158]
**Describe the bug**

`Error Details: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup workflow-frontend on 10.0.0.10:53: no such host"`

Upon launching a fresh deployment in a non-default namespace, it appears my admintools service lacks a valid `TEMPORAL_CLI_ADDRESS` envvar.  The one set does not match the services launched.  I don't know the full effects of the issue but I know when I exec into the container, I need to manually set the env var to a valid hostname.

**To Reproduce**
1. Launch a chart into a non-default namespace with the `temporal` chart as a dependency.
   `helm install workflow -n workflow ./ --create-namespace`
2. Exec into the `admintools` pod
   `kubectl exec -it -n workflow services/workflow-temporal-admintools /bin/bash`
3. List your namespaces
   `tctl namespace list`
4. This should fail with a `no such host`.

**Expected behavior**
A list of declared namespaces.

**Screenshots/Terminal ouput**
```bash
% kubectl exec -it -nworkflow services/workflow-temporal-admintools /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
bash-5.0# tctl namespace list
Error: Error when list namespaces info
Error Details: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup workflow-frontend on 10.0.0.10:53: no such host"
('export TEMPORAL_CLI_SHOW_STACKS=1' to see stack traces)

# export TEMPORAL_CLI_ADDRESS=workflow-temporal-frontend:7233

# tctl namespace list
Name: temporal-system
...
...
```

**Versions (please complete the following information where relevant):**
 - OS: Linux
 - Temporal Version: 1.7.0
 - are you using Docker or Kubernetes or building Temporal from source?  Kubernetes

**Additional context**
The web deployment follows a different pattern:

https://github.com/iamjohnnym/helm-charts/blob/master/templates/web-deployment.yaml#L38

**Comment by robholland** [comment]
Fixed in #159
