### ISSUE TITLE
[Bug] Docker images not available

### ISSUE THREAD

**Issue by anpolychrono** [temporalio/helm-charts#166]
**Describe the bug**

Pods can not download docker images.

**To Reproduce**
1. helm install \
>     --set server.replicaCount=1 \
>     --set cassandra.config.cluster_size=1 \
>     --set prometheus.enabled=false \
>     --set grafana.enabled=false \
>     --set elasticsearch.enabled=false \
>     --set kafka.enabled=false \
>     temporaltest . --timeout 15m

**Expected behavior**
To see all pods up and Running

**Screenshots/Terminal ouput**

kubectl get pods
NAME                                       READY   STATUS                  RESTARTS   AGE
temporaltest-admintools-7d58dc8455-9zzfp   0/1     ContainerCreating       0          37s
temporaltest-cassandra-0                   0/1     ErrImagePull            0          37s
temporaltest-frontend-57d9458c7c-ntwvs     0/1     Init:ImagePullBackOff   0          37s
temporaltest-history-79c944d586-m6nwj      0/1     Init:ImagePullBackOff   0          37s
temporaltest-matching-687d4bdd6c-8qbvx     0/1     Init:0/4                0          37s
temporaltest-schema-setup-rp5w4            0/2     Init:ErrImagePull       0          37s
temporaltest-web-6d47bff77d-dbl66          0/1     ImagePullBackOff        0          37s
temporaltest-worker-7fd7db64fc-gxg6s       0/1     Init:ImagePullBackOff   0          37s 

kubectl describe pod temporaltest-cassandra-0
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  54s                default-scheduler  Successfully assigned default/temporaltest-cassandra-0 to kind-worker2
  Warning  Failed     26s                kubelet            Failed to pull image "cassandra:3.11.3": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/cassandra:3.11.3": failedto copy: httpReaderSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/cassandra/manifests/sha256:ce85468c5badfa2e0a04ae6825eee9421b42d9b12d1a781c0dd154f70d1ca288: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Warning  Failed     26s                kubelet            Error: ErrImagePull
  Normal   BackOff    25s                kubelet            Back-off pulling image "cassandra:3.11.3"
  Warning  Failed     25s                kubelet            Error: ImagePullBackOff
  Normal   Pulling    11s (x2 over 53s)  kubelet            Pulling image "cassandra:3.11.3"

Though I can download the cassandra using same docker account as above: 

docker pull docker.io/library/cassandra:3.11.3
3.11.3: Pulling from library/cassandra
6ae821421a7d: Pull complete
a0fef69a7a19: Pull complete
6849fd6936d9: Pull complete
832b4e4feae8: Pull complete
12e36f0fa0d9: Pull complete
625655f45ec7: Pull complete
c4392f7e9b96: Pull complete
4f6f85e6e245: Pull complete
e60258d103eb: Pull complete
30a7210918ab: Pull complete
Digest: sha256:ce85468c5badfa2e0a04ae6825eee9421b42d9b12d1a781c0dd154f70d1ca288
Status: Downloaded newer image for cassandra:3.11.3
docker.io/library/cassandra:3.11.3

**Versions (please complete the following information where relevant):**
 - OS: Linux
 - Temporal Version : 1.8.2
 - are you using Docker or Kubernetes or building Temporal from source? Running on kind 

**Additional context**

**Comment by joebowbeer** [comment]
Because of Docker Hub Rate Limiting.

Perhaps temporalio should also publish images to quay.io?

**Comment by underrun** [comment]
yes this is dockerhub rate limits - our suggestion would be to create an account on dockerhub and supply image pull credentials:

https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

alternately it's possible to cache images and push them to nodes and adjust image pull policy, set up your own image registry, or decrease the frequency with which you hit dockerhub.
