### ISSUE TITLE
[Bug] Easy way to use chart with Postgresql

### ISSUE THREAD

**Issue by alenkacz** [temporalio/helm-charts#174]
**Describe the bug**
I was trying to disable cassandra and use the chart with postgresql easily. Looks like it cannot be done because of server-job template.

**To Reproduce**
1. Download 1.9.1 release of the chart
2. Try to install with 
```
helm install \
    --set server.replicaCount=1 \
    --set cassandra.enabled=false \
    --set elasticsearch.enabled=false \
    --set kafka.enabled=false \
    --set postgresql.enabled=true \
    temporaltest . --timeout 15m
```
3. got `Error: execution error at (temporal/templates/server-job.yaml:92:24): Please specify cassandra port for default store`

**Expected behavior**
Temporal starts without cassandra but with postgresql.

**Versions (please complete the following information where relevant):**
 - OS: Max
 - Temporal Version 1.9.1
 - are you using Docker or Kubernetes or building Temporal from source?

**Additional context**

**Comment by alenkacz** [comment]
figured it out, sorry :) need to disable schema update

**Comment by AlHood77** [comment]
@alenkacz I'm getting same error message and using postgres also.  I have schema set to false in my values.yaml.

**Comment by dperetti** [comment]
> figured it out, sorry :) need to disable schema update

Still sounds like a bug!
