### ISSUE TITLE
[Feature Request] Approaching Official PostgreSQL 9.6 EOL Date

### ISSUE THREAD

**Issue by iamjohnnym** [temporalio/helm-charts#180]
**Is your feature request related to a problem? Please describe.**

PostgreSQL has an EOL date of `November 11, 2021`.  Officially, the temporal platform seems to support PostgreSQL only @v9.6.

https://docs.temporal.io/docs/server/versions-and-dependencies/#persistence
https://www.postgresql.org/support/versioning/

**Describe the solution you'd like**

Official verbiage that more recent versions have been tested and are deemed validated as a supported database.

**Additional context**

[PostgreSQL EOL](https://www.postgresql.org/support/versioning/)
[Temporal Supported Databases](https://docs.temporal.io/docs/server/versions-and-dependencies/#persistence)

**Comment by sw-yx** [comment]
thanks for this heads up :) Looks like we'll have to move to testing against Postgres 10/11/12/13 soon - cc @samarabbas @alexshtin

**Comment by sw-yx** [comment]
we now fully support pg 10-14
