### ISSUE TITLE
[Feature Request] Split out dependencies from chart and create separate dev chart with dependencies

### ISSUE THREAD

**Issue by underrun** [temporalio/helm-charts#189]
Currently parts of our helm chart are production ready and parts are development only. This makes it difficult to communicate clearly about the status of the chart.

To fix this we would like to shift this repo to house 2 charts: one production ("temporal") for only the temporal services, and another for development ("temporal-development-deps") that is more like the current chart but consumes the to-be-created temporal service only chart as a dependency along side the other dependencies.

After doing this we would also like to set up real helm releases for our charts.

**Comment by sagikazarmark** [comment]
Are there any plans to work on this in the near future? I'll install a couple temporal instances in the near future and I'd like to get rid of all the "junk" that's currently included in the chart. I'd be willing to provide a PR, but I'd really like to avoid wasting all that work and keep rebasing it for weeks (looking at the number of open PRs; such restructure will potentially conflict with every current PR).

So first question is if you accept PRs for this in the first place and if I send a PR splitting the current chart into two, can you commit to a timely review and merge? I understand if you can't (roadmap, summer, whatever), but (as I mentioned) I won't start working on it if it all goes to waste. Thanks!

**Comment by sw-yx** [comment]
@mark its a fair question - ownership for this repo has been unclear up til now but we are in the process of handing over to my team. Ultimately we are struggling with clearly communicating what we will or will not accept as we don't want to offer a franken-helm chart that offers all the things - much rather people modify it themselves with some nice examples/pointers from the community. really appreciate your willingness to contribute and we know this area is something we need to work on.

**Comment by sagikazarmark** [comment]
@sw-yx a couple thoughts that might help you make those decisions:

IMO the current chart is not a very good example for people to start. I'm pretty sure everyone running Kubernetes have their own Prometheus, Grafana, etc installed, so having these components in the chart is more bloat than useful, not to mention it's more work for people to make it "production-ready".

Looking at the success of the original Cadence chart, I'd say there _is_ a demand from the community for a chart that they can use out of the box. It was the only publicly available resource for installing Cadence for quite some time, so it was extremely popular.

It also demonstrates that it's possible to create a chart to install a production-ready Cadence/Temporal cluster that works out of the box.

Last, but not least: having an official chart means that people can help each other. If everyone has to cook their own, it's much harder.

I guess the question you need to answer is whether you want to maintain a Helm chart or not. I think it would be beneficial for the community, but I can understand if it's not your primary way to deliver Temporal.

I'd be happy to help steer the Helm chart/Kubernetes operations boat if you decide you want to keep these things around.

**Comment by laertispappas** [comment]
hi @sw-yx  any updates on this one? Mainly I would be interested in having the Chart repository which as is now I use a forked version on gh-pages but I also value @sagikazarmark feedback and willingness to assist here.

**Comment by robholland** [comment]
I don't think it's likely we'll offer two versions of the chart, but I do think that soon we will drop prometheus and grafana dependencies.

**Comment by robholland** [comment]
Helm charts are being published now. Once we hit 1.0 (expected soon) we will switch publishing to artifacthub.io. We won't be doing dev vs prod charts. Grafana and Prometheus will be removed from the chart for 1.0.
