### ISSUE TITLE
Connection with password protected ElasticSearch 

### ISSUE THREAD

**Issue by ASHISH932** [temporalio/helm-charts#197]
**Describe the bug**
Getting issue while connecting with an external Elasticsearch, which expects username password as an input. The connection of temporal server with an external elastic search that does not require password is working fine, but when trying with a password protected one, it is giving error. This error occur when a request to elasticsearch is made without username password.

**To Reproduce**
1. Install Elastic Search and enabe authentication
2. Set the variable properly of the elastic Search

**Expected behavior**
Temporal server should interact with elastic search by adding username password.

**Screenshots/Terminal ouput**
`{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/_template/temporal-visibility-template]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/_template/temporal-visibility-template]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/prod-temporal-visibility]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/prod-temporal-visibility]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}{"level":"info","ts":"2021-06-08T13:18:36.909Z","msg":"Updated dynamic config","logging-call-at":"file_based_client.go:262"}`

**Versions (please complete the following information where relevant):**
 - OS: Linux
 - Docker Server Version:- 1.9.2
 - Using helm-chart to start Temporal server

**Additional context**

The environment variable of username, password asked by the helm chart is also getting properly set in the containers, verified by echoing it.

**Comment by robholland** [comment]
The chart has changed a lot since this issue was filed, please re-open if this issue persists with the current version.
