### ISSUE TITLE
[Bug] Unable to disable elastic authentication

### ISSUE THREAD

**Issue by eufebius** [temporalio/helm-charts#200]
**Describe the bug**
If external elasticsearch is used, u cannot disable user authentification and becauser of that init containers will fail during ES checks ( e.g. aws es service )

**To Reproduce**
1. Deploy with external ES without username, password
2. Check check-elasticsearch-index init container in server deployment
3. See error

**Expected behavior**
Add possibility to continue without username, password

**Comment by robholland** [comment]
I believe https://github.com/temporalio/helm-charts/pull/522 fixes this as while username and password will still be sent, they will be sent empty. It is my understanding that Elasticsearch will be content with this if auth was not enabled. Please re-open if this is not the case.
