### ISSUE TITLE
[Bug] Wrong ES template creation

### ISSUE THREAD

**Issue by FedeBev** [temporalio/helm-charts#206]
**Describe the bug**
In v1.10.5 tha path of the ES index template is `schema/elasticsearch/v7/visibility/index_template.json` and not `schema/elasticsearch/visibility/index_template_v7.json`, therefore the temporal-es-index-setup does not set up ES correctly.

Moreover, the default index name `temporal_visibility_v1_dev` in the values gives a wrong hint because the index template wouldn't match the index since the index pattern has the following values:

``` yaml
"index_patterns": [
    "temporal-visibility-*"
  ],
```

**To Reproduce**
Just perform a clean deployment from the current master (eac55bf)

**Expected behavior**
Create the right index template

**Screenshots/Terminal ouput**
```text
Warning: Couldn't read data from file 
Warning: "schema/elasticsearch/visibility/index_template_v7.json", this makes 
Warning: an empty POST.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   163  100   163    0     0   4657      0 --:--:-- --:--:-- --:--:--  4657
{"error":{"root_cause":[{"type":"parse_exception","reason":"request body is required"}],"type":"parse_exception","reason":"request body is required"},"status":400}  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    85  100    85    0     0    310      0 --:--:-- --:--:-- --:--:--   310
(reverse-i-search)`9': kubectl -n daisy logs -f telemetry-ingestor-6fdb9cf68^C4wnks telemetry-ingestorards_acknowledged":true,"index":"temporal_visibility_v1_dev"}
```

**Comment by alexshtin** [comment]
During short period of time `master` branch on the helm-chats side didn't work with latest release of the server. Actually `master` branch should not be used with the latest server release. Specific release in this repo should be used with corresponding release of the server.

Anyway, it should work fine with 1.11.x.
