### ISSUE TITLE
Fix docker config permissions

### ISSUE THREAD

**Issue by mfateev** [temporalio/helm-charts#22]
From slack:

> Hi,  We tested cadence in an openshift environement; we have used the banzaichards cloud for cadence helm chard.(only supported with kubernetes). In fact it doesn't work on openshift.....but I small change in dockerfile makes it working under openshift.   Could you add this on your dockerfile (FROM ubercadence/server:0.11.0
>  RUN chmod 775 /etc/cadence/config)   . This chmod is not a problem with kubernetes and I will work on openshift . It's a win-win change I think.

**Comment by sw-yx** [comment]
closing for now. pls reopen if issue.
