### ISSUE TITLE
Temporal Visibility Keyspace Schema Setup Failing

### ISSUE THREAD

**Issue by vaddempudisr** [temporalio/helm-charts#226]
### Describe the bug

Installing temporal server with our own Cassandra (operated in AWS)

Using temporal-cassandra-tool to create and setup cassandra keyspaces (temporal and temporal visibility)

As part of that running these commands 

./temporal-cassandra-tool create-Keyspace -k temporal
CASSANDRA_KEYSPACE=temporal ./temporal-cassandra-tool setup-schema -v 0.0
CASSANDRA_KEYSPACE=temporal ./temporal-cassandra-tool update -schema-dir schema/cassandra/temporal/versioned

./temporal-cassandra-tool create-Keyspace -k temporal_visibility

It's all good untill these below two commands. Throwing an error _error listing schema dir:no subdirs found with version >= 1.5_

CASSANDRA_KEYSPACE=temporal_visibility ./temporal-cassandra-tool setup-schema  -v 0.0
CASSANDRA_KEYSPACE=temporal_visibility ./temporal-cassandra-tool update -schema-dir schema/cassandra/visibility/versioned

### Expected behavior

It should create the schema for temporal_visibility keyspace as it is creating for temporal keyspace

### Screenshots/Terminal output
```temporal-cassandra-tool setup-schema -v 0.0 CASSANDRA_KEYSPACE=temporal_visibility
2021/09/15 15:37:50 validating connection to cassandra cluster
2021/09/15 15:37:50 connection validation succeeded
2021/09/15 15:37:50 Starting schema setup, config=&{SchemaFilePath: InitialVersion:0.0 Overwrite:false DisableVersioning:false}
2021/09/15 15:37:50 Setting up version tables
2021/09/15 15:37:50 Current database schema version 1.5 is greater than initial schema version 0.0. Skip version upgrade
2021/09/15 15:37:50 Schema setup complete```

temporal-cassandra-tool update-schema -d /etc/temporal/schema/cassandra/visibility/versioned
2021/09/15 15:37:10 validating connection to cassandra cluster
2021/09/15 15:37:10 connection validation succeeded
2021/09/15 15:37:10 UpdateSchemeTask started, config=&{DBName: TargetVersion: SchemaDir:/etc/temporal/schema/cassandra/visibility/versioned IsDryRun:false}
2021/09/15 15:37:10 error listing schema dir:no subdirs found with version >= 1.5
```
### Versions

- OS: Linux
- Temporal Version 1.12.0 or 1.9.2 (both are getting the same issue)
- Are you using Docker or Kubernetes or building Temporal from source? Kubernetes

**Comment by mo-dayyeh** [comment]
I'm having the same issue when using cassandra , I'm using cassandra 0.15.4 chart and as I'm using crossplane in the deployment of the child charts : crossplane , cassandra  , the temporal schema update job get stuck forever waiting , when I delete the job the chart deploys but the issue cassandra schema setup never get executed although its enabled, I endup with a broke chart as the frontend and backend , worker ..etc not working , only the web comes up , any idea how can I fix this ?

**Comment by mo-dayyeh** [comment]
I resolved this issue at least for me by removing pre-upgrade from the helm hook , the issue didn't happen when installing the chart using helm manually but it happens if using  argocd ..etc 
My assumption is most people probably faced that , I haven't managed to solve until I removed the pre-upgrade which allowed it work , also a trick was to turn off the schema update option and only enable the setup , then enable both after setup is done

**Comment by robholland** [comment]
Cassandra is no longer supported for visibility.

**Comment by chacon** [comment]
I found visibility still in the [values for the latest released chart](https://github.com/temporalio/helm-charts/blob/main/charts/temporal/values.yaml#L151-L167), so just wanted to confirm that support for cassandra has not been brought back

**Comment by robholland** [comment]
That's a bug in the chart (well, values), it has not been brought back, and there are no plans to do so.
