### ISSUE TITLE
Publish helm charts repo via GitHub pages

### ISSUE THREAD

**Issue by andrey-dubnik** [temporalio/helm-charts#229]
Hi, I was looking at the option to consume helm in a bit more convenient way which is possible via the GitHub pages and Helm releaser action. In order to implement that I've refactored the current helm repo in a way which would make a deployment flexible with possibility to add more charts on a later stage if needs to.

Repo reference: https://github.com/andrey-dubnik/helm-charts
Helm landing page: https://andrey-dubnik.github.io/helm-charts/

This way you can add helm as `helm repo add temporalio https://temporalio.github.io/helm-charts`

I can make a PR if this is Ok

**Comment by underrun** [comment]
this is definitely in plan

**Comment by joebowbeer** [comment]
For background and previous PR:

* https://github.com/temporalio/helm-charts/issues/45
* https://github.com/temporalio/helm-charts/pull/147

**Comment by IkePCampbell** [comment]
Any news on this?

**Comment by pzduniak** [comment]
This still makes it incredibly annoying to deploy Temporal in systems that rely on Helm repos.

Please dedicate the couple hours of effort to set it up. I did it for https://github.com/mailgun/gubernator.

**Comment by froblesmartin** [comment]
A similar issue exists, it would be better to close one so that there is a single place to comment on the Helm chart publication
https://github.com/temporalio/helm-charts/issues/45

**Comment by robholland** [comment]
We now publish to https://go.temporal.io/helm-charts

**Comment by monotek** [comment]
OCI images would be nice too :)
