### ISSUE TITLE
[Feature Request] Upgrade ingress-web to use new api version

### ISSUE THREAD

**Issue by naormatania** [temporalio/helm-charts#235]
### Is your feature request related to a problem? Please describe.

According to https://kubernetes.io/blog/2021/07/26/update-with-ingress-nginx/ since kubernetes 1.22 `Ingress` object won't be accessible from `networking.k8s.io/v1beta1 ` but only through `networking.k8s.io/v1`.

Running temporal-web with `ingress` enabled on minikube v1.23.2 (kubernetes v1.22.1) fails for this reason.

### Describe the solution you'd like

Check in https://github.com/temporalio/helm-charts/blob/master/templates/web-ingress.yaml if it has api version of `networking.k8s.io/v1` and fix yaml accordingly

**Comment by robholland** [comment]
Fixed by #278
