### ISSUE TITLE
[Feature Request] Allow specifying TLS configuration

### ISSUE THREAD

**Issue by sd-hypredge** [temporalio/helm-charts#294]
### Is your feature request related to a problem? Please describe.
The ability to specify and configure TLS options is documented (https://docs.temporal.io/docs/server/configuration/#tls) but not implemented in the charts

### Describe the solution you'd like
Ability to configure and MTLS options in values.yaml

**Comment by sd-hypredge** [comment]
The capability is just an incremental change over existing chart, hence I have not submitted a formal proposal. 
I have an implementation that follows the outline of the mechanics described in the documentation (https://docs.temporal.io/docs/server/configuration/#tls) , and serves the use case . I will contribute a PR if the feature request is prioritized for implementation

**Comment by lerminou** [comment]
Hi, I made a PR a long time ago but closed because they wanted to revamp the project ...
https://github.com/temporalio/helm-charts/pull/162

**Comment by joshbranham** [comment]
What is the chances the original proposed PR can be re-opened? This proposal is now closed, which leads me to believe nobody internal is working on it. https://github.com/temporalio/proposals/issues/42

**Comment by robholland** [comment]
I believe all aspects of this are now supported by the current chart. Please re-open if this is not the case and I will work with you to get whatever is missing sorted.
