### ISSUE TITLE
Issue while installing helm chart

### ISSUE THREAD

**Issue by sreepadmaparamesvaraiyer** [temporalio/helm-charts#296]
I am trying to install the temporal helm chart and I am getting the below error

C:\Users\sreepadma.paramesvar\Downloads\helm-v3.9.0-rc.1-windows-amd64\windows-amd64>helm repo add temporal https://github.com/temporalio/helm-charts
Error: looks like "https://github.com/temporalio/helm-charts" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/temporalio/helm-charts/index.yaml : 404 Not Found

Can you please help?

**Comment by lksmrqrdt** [comment]
This relates to #45, as there's no Helm Chart published within a Helm Repository yet.  
If you want to use the Chart within your own Subchart, you'll have to [use it manually](https://helm.sh/docs/topics/charts/#managing-dependencies-manually-via-the-charts-directory).

**Comment by robholland** [comment]
We now publish to a repo. You can use `helm install --repo http://go.temporal.io/helm-charts mytemporal temporal`
