### ISSUE TITLE
 error calling include: template: no template "cassandra.fullname" associated with template "gotpl"

### ISSUE THREAD

**Issue by Revanthchowdary9** [temporalio/helm-charts#297]
I am getting the below error while  i am trying to install the chart 

Error: INSTALLATION FAILED: template: temporal/templates/server-job.yaml:46:51: executing "temporal/templates/server-job.yaml" at <include "cassandra.host" $>: error calling include: template: temporal/templates/_helpers.tpl:350:22: executing "cassandra.host" at <include "call-nested" (list . "cassandra" "cassandra.fullname")>: error calling include: template: temporal/templates/_helpers.tpl:69:4: executing "call-nested" at <include $template (dict "Chart" (dict "Name" $subchart) "Values" (index $dot.Values $subchart) "Release" $dot.Release "Capabilities" $dot.Capabilities)>: error calling include: template: no template "cassandra.fullname" associated with template "gotpl"

kindly can anyone help me on this

**Comment by lerminou** [comment]
I have the same problem

**Comment by lerminou** [comment]
Hi @jaxxstorm, the Cassandra dependency is an old incubator helm not maintained anymore and not used in our case because we use an external Cassandra database.

It should be better to integrate the helper in the chart here.

**Comment by jaxxstorm** [comment]
Agreed, that's just what I did to get things working

**Comment by robholland** [comment]
Having to run `helm dependencies update` is expected and documented behaviour.
