### ISSUE TITLE
[Feature Request] Enable LivenessProbe for workers

### ISSUE THREAD

**Issue by gracco** [temporalio/helm-charts#298]
### Is your feature request related to a problem? Please describe.

When we deploy a new cluster, the workers nodes don't have a LivenessProbe because it's explicit configured in the code to not add them.

### Describe the solution you'd like

Remove the if loop in the lines above. Or implement a specific livenessProbe for workers.

https://github.com/temporalio/helm-charts/blob/master/templates/server-deployment.yaml#L127-L132
```
{{- if ne $service "worker"}}
          livenessProbe:
             initialDelaySeconds: 150
             tcpSocket:
               port: rpc
 {{- end }}
```

**Comment by robholland** [comment]
Workers don't have a listener to probe.
