### ISSUE TITLE
local cluster metadata rpcAddress does not match the frontend endpoint

### ISSUE THREAD

**Issue by andrey-dubnik** [temporalio/helm-charts#317]
Hi,

In the new scheduler feature having the rpcAddress setup to the correct endpoint is essential as otherwise schedule workflow fails to run the scheduled jobs as it uses this info to connect to a Frontend. Changing this value post server build is a pain hence it would be better if one is set correctly from the start.

Currently the rpcAddress is set to the Cadence default port where it should be set similar to the way public client is setup in order for the scheduler to connect to the same endpoint with the system worker.

https://github.com/temporalio/helm-charts/blob/e9dc0d001c5df7f1f3672e0eb9c2508e14c723ac/templates/server-configmap.yaml#L156

Thanks,
A

**Comment by dnr** [comment]
FYI, this shouldn't be an issue any more after server 1.18 (soon to be released). The current cluster `rpcAddress` will be ignored and it'll use only either `publicClient.hostPort` or the internal membership service resolver, with whatever TLS you've configured for local frontend connections.

**Comment by andrey-dubnik** [comment]
That will be great. 

Is this property plays any other role in the system in case some other problem related to it surfaces?

**Comment by robholland** [comment]
Fixed by #497.
