### ISSUE TITLE
Helm-Chart Release 1.19.0 uses temporalio/server tag=1.18.5

### ISSUE THREAD

**Issue by max-matiukhin** [temporalio/helm-charts#344]
### What are you really trying to do?
I've tried to use helm chart release 1.19.0 and expected it to use temporalio/server 1.19.0

### Describe the bug
Temporal's helm-chart release 1.19.0 uses `server` and `admin-tools` version 1.18.5
I know that I can change the version myself in the values-file,  however, it is unclear if it was done intentionally.
Is there any problem with temporalio/server 1.19.0?

**Comment by mindaugasrukas** [comment]
Those are default values. And you can override any value using the `--set` option. For example: `--set server.image.tag=1.19.0`. That is a better practice than relying on the default values.

**Comment by joebowbeer** [comment]
@mindaugasrukas wrote:

> Those are default values. And you can override any value using the `--set` option. For example: `--set server.image.tag=1.19.0`. That is a better practice than relying on the default values.

Going forward, I hope the server tag in the provided (default) values.yaml matches the `appVersion` in Chart.yaml

```yaml
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.19.0
```
