### ISSUE TITLE
[Feature Request] Support special characters in elasticsearch credentials

### ISSUE THREAD

**Issue by tluimes** [temporalio/helm-charts#348]
### Support Special Characters in Elasticsearch Credentials

Some special characters are not supported for elasticsearch credentials, as they're not supported by the curl command used by init containers when unquoted.

ex:
```
until curl --silent --fail --user temporal:T(e-Pa$$word https://elasticsearch-cluster:443/temporal_visibility_v1 2>&1 > /dev/null; do echo waiting for elasticsearch index to become ready; sleep 1; done;
sh: syntax error: unexpected "(" (expecting "do")
```

### Describe the solution you'd like

- Add quotes around password and username to allow the use of special characters. 
- Ideally an environment variable would be used for the credentials to prevent displaying credentials when running `kubectl describe pod`

**Comment by robholland** [comment]
Fixed in #522
