### ISSUE TITLE
[Bug] Incorrect Usage of `temporal-sql-tool` described in README

### ISSUE THREAD

**Issue by lauerdev** [temporalio/helm-charts#364]
### What are you really trying to do?

Update the README to match the correct usage of the tool.

### Describe the bug

The README describes two usages of the `temporal-sql-tool create-database` command:
`./temporal-sql-tool create-database -database temporal`
`./temporal-sql-tool create-database -database temporal_visbility`

However, per the tool's help page global arguments must be supplied prior to any commands:
```
NAME:
   temporal-sql-tool - Command line tool for temporal sql operations

USAGE:
   temporal-sql-tool [global options] command [command options] [arguments...]
```

Supplying the `-database` argument after the `create-database` command results in an "Incorrect Usage" error:
`Incorrect Usage: flag provided but not defined: -database`

The two usages in the README should be reordered as follows:
`./temporal-sql-tool -database temporal create-database`
`./temporal-sql-tool -database temporal_visbility create-database`

### Minimal Reproduction

N/A

### Environment/Versions

- OS and processor: Linux
- Temporal Version: 1.18.4
- Are you using Docker or Kubernetes or building Temporal from source? No

**Comment by nkranes-frameio** [comment]
> `./temporal-sql-tool -database temporal_visbility create-database`

`temporal_visibility`
