### ISSUE TITLE
[Feature Request] Helm chart in production

### ISSUE THREAD

**Issue by PeteMac88** [temporalio/helm-charts#367]
Hey there,
we are currently looking at temporal to manage workflows for our microservices. While looking at the helm chart I came across the note in the README "We do not recommend using Helm for managing Temporal deployments in production". The link to the discussion does not work anymore. Is this still up-to-date? Does anyone know why they dont recommend this?

**Comment by ElanHasson** [comment]
See https://web.archive.org/web/20221001133521/https://temporal.io/blog/temporal-and-kubernetes

**Comment by mindaugasrukas** [comment]
Duplicate: #371
