### ISSUE TITLE
[Bug] https://temporal.io/blog/temporal-and-kubernetes is 404

### ISSUE THREAD

**Issue by ukd1** [temporalio/helm-charts#371]
### What are you really trying to do?

Read the readme

### Describe the bug

One of the first links explaining if you should use these chats in production 404s

### Minimal Reproduction

click the link "[See our recent discussion on this topic](https://temporal.io/blog/temporal-and-kubernetes)" in the 3rd para of the readme

### Environment/Versions

n/a

### Additional context

n/a

**Comment by lorensr** [comment]
Thanks for reporting! I've removed the dead link and updated the README to say that the only portions of the helm chart that are production ready are the parts that configure and manage Temporal Server itself—not Cassandra, Elasticsearch, Prometheus, or Grafana.
