### ISSUE TITLE
[Bug] Pods unable to reach Cassandra during Init

### ISSUE THREAD

**Issue by guptamridul1809** [temporalio/helm-charts#373]
### What are you really trying to do?

I'm trying to run temporal using helm chart
`helm install     --set server.replicaCount=1     --set cassandra.config.cluster_size=1     --set prometheus.enabled=false     --set grafana.enabled=false     --set elasticsearch.enabled=false     temporaltest . --timeout 150m`

### Describe the bug

Several pods are stuck in init state
<img width="564" alt="image" src="https://user-images.githubusercontent.com/97242793/228215380-cb6dc8c5-02b0-47c0-a625-c437011203d1.png">

I let it try and complete for over an hour, no progress though

On further inspection, it was found that all the pods are waiting for cassandra nslookup to succeed
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/97242793/228290840-8bd18165-0fe3-4a04-93df-88c803f3c6b1.png">

### Minimal Reproduction

Just running
`helm install     --set server.replicaCount=1     --set cassandra.config.cluster_size=1     --set prometheus.enabled=false     --set grafana.enabled=false     --set elasticsearch.enabled=false     temporaltest . --timeout 150m` gives this error
I tried with latest master and with `release 1.12` to consider an older setup, both setups run into same issue

### Environment/Versions

OS:
<img width="322" alt="image" src="https://user-images.githubusercontent.com/97242793/228191142-491d8c15-a363-454c-bc9e-98ac79d8f536.png">

Docker:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/97242793/228191262-b12e67d4-8037-4edf-b83e-50621b5267d6.png">

Minikube:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/97242793/228191339-eaa1558e-7038-49bb-a3a8-70548142b38d.png">

Helm:
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/97242793/228192037-169773fd-ded9-4323-ab27-999096ef17ed.png">

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by mindaugasrukas** [comment]
Investigating. I see similar behavior with one difference - it's not being stuck waiting for Cassandra nslookup to succeed, but for schema being populated.

**Comment by chaychoong** [comment]
Based on [this](https://github.com/temporalio/helm-charts/blob/890fe3868bb5044110a8028b58c9a94e4e4bd337/templates/server-job.yaml#L17) line, the job to perform the schema-setup will only start after everything is loaded. Which can't happen because the rest of the server components depend on having schema be set up.

@mindaugasrukas

**Comment by mindaugasrukas** [comment]
I think those hooks are correct. According to this document: https://helm.sh/docs/topics/charts_hooks/#hooks-and-the-release-lifecycle, "loaded" doesn't mean it's blocking.

```
1. User runs helm install foo
2. The Helm library install API is called
3. CRDs in the crds/ directory are installed
4. After some verification, the library renders the foo templates
5. The library prepares to execute the pre-install hooks (loading hook resources into Kubernetes)
6. The library sorts hooks by weight (assigning a weight of 0 by default), by resource kind and
   finally by name in ascending order.
7. The library then loads the hook with the lowest weight first (negative to positive)
8. The library waits until the hook is "Ready" (except for CRDs)
9. The library loads the resulting resources into Kubernetes. Note that if the --wait flag is set,
   the library will wait until all resources are in a ready state and will not run the post-install hook
   until they are ready.
10. The library executes the post-install hook (loading hook resources)
11. The library waits until the hook is "Ready"
12. The library returns the release object (and other data) to the client
13. The client exits

What does it mean to wait until a hook is ready? This depends on the resource declared in the hook.
If the resource is a Job or Pod kind, Helm will wait until it successfully runs to completion. And if the
hook fails, the release will fail. This is a blocking operation, so the Helm client will pause while the
Job is run.

For all other kinds, as soon as Kubernetes marks the resource as loaded (added or updated),
the resource is considered "Ready".
```

But I see your point of making it a non-hook job and load together with all other resources.

**Comment by mindaugasrukas** [comment]
@guptamridul1809, @chaychoong, could you try adding `--set debug=true` to the helm command and paste schema-setup and schema-update Job logs? For me, they report success, but the schema is actually not loaded. I want to make sure you are having the same issue.
Also, this issue is flaky on my side. Hence, I'm unsure if removing the `helm.sh/hook` annotation is related here.

**Comment by robholland** [comment]
Closing due to lack of feedback. Please re-open if this issue persists with the current chart version.
