### ISSUE TITLE
[Bug] ServiceAccount does not act as it should when adding external account

### ISSUE THREAD

**Issue by vongohren** [temporalio/helm-charts#403]
### What are you really trying to do?

Im adding a GCP cloud proxy sidecar, and have setup [workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) for the cluster. All I want is to specify which KSA(Kubernetes service account) the deployment shall use.

So when I set create to false, makes sense because it already exists, I want the service account name to still be created.

Therefor create false and name mySAname.

But because of the helpers, nothing will be created, and the service account wont be added.

It can be solved with a simple else, but just want to hear your thoughts on this. 
It has been done here: https://github.com/tryretool/retool-workflows-helm/blob/main/values.yaml#L273 and with this helper: https://github.com/tryretool/retool-workflows-helm/blob/main/templates/_helpers.tpl#L56

### Describe the bug

The sa name should still be added to the right places its expected

### Minimal Reproduction

Just change serviceAccount in values.yaml, keep create: false, but add a name.
Run with template --debug, and you can see that there is an empty line where the name should be.

### Environment/Versions

No relevant info

### Additional context

No additional context

**Comment by christopher-wong** [comment]
+1 the current Helm chart will not add an existing service-account when `serviceAccount.create: false`

**Comment by vongohren** [comment]
How do one go about moving this forward?

**Comment by esn89** [comment]
Hi @vongohren 

I saw that you attempted to do workload identity.  Did you have any success?  If so, do you have any examples of your helm charts?

I am currently trying that out myself, namely with the CloudSQL Proxy.

**Comment by vongohren** [comment]
@esn89 you are asking a good question! Its such a long time since I did this so I cant really answer. Im sorry.

But it seems they did some PR merging to get it working
