### ISSUE TITLE
[Feature Request] Support passing ImagePullSecrets to Temporal Web Deployment Helm Template

### ISSUE THREAD

**Issue by mustaFAB53** [temporalio/helm-charts#419]
### Is your feature request related to a problem? Please describe.

[Temporal web Kubernetes deployment manifest / helm template](https://github.com/temporalio/helm-charts/blob/master/templates/web-deployment.yaml) do not support passing `imagePullSecrets`.
A support needs to be added for the same as temporal web images can be expected to be fetched from private registries

### Describe the solution you'd like

Add required support similar to the one already provided in [temporal server deployment manifest](https://github.com/temporalio/helm-charts/blob/master/templates/server-deployment.yaml#L156)

**Comment by mustaFAB53** [comment]
Hi Team
Any updates here.. I can raise the PR for the same if this feature seems relevant to you

**Comment by GerardoMoraS** [comment]
Hello guys, I forgot to add a comment here, but I added a PR to implement this feature.

**Comment by robholland** [comment]
Fix was merged.
