### ISSUE TITLE
web-ingress.yaml tls and rules indentation

### ISSUE THREAD

**Issue by sandeeppaul-1994** [temporalio/helm-charts#42]
in the web-ingress.yaml, 

the tls and rules key is in the same indentation as the spec. Due to which the install is failing.

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress): unknown field "rules" in io.k8s.api.networking.v1beta1.Ingress, ValidationError(Ingress): unknown field "tls" in io.k8s.api.networking.v1beta1.Ingress]

kindly change the indentation.

**Comment by sw-yx** [comment]
should be fixed now thanks.
