### ISSUE TITLE
[Feature Request] Add option to create default namespace

### ISSUE THREAD

**Issue by lorensr** [temporalio/helm-charts#420]

**Comment by YannickZ** [comment]
This would be a really nice feature, today we are forced to do it manually. IMHO there should be an option on the helmcharts to set up this too :)

**Comment by debugger24** [comment]
I can pick this up and raise a PR for this feature.

**Comment by daniel347x** [comment]
Putting in my 2 cents for this - I'm rapidly integrating TemporalIO for use in our production systems and need to demo a prototype soon; having obvious features like Helm flags to support creating namespaces without having to add a completely new part of the Kubernetes deployment scripts to download the CLI just to execute a single command seems like a no-brainer. This is certainly costing me time now.

Thanks for the awesome framework!

**Comment by mananmangal** [comment]
I would like to work on this issue.
Created a PR to update the server-job setup job to provide an option to create default namespace.
