### ISSUE TITLE
[Feature Request] HTTP API Service exposure

### ISSUE THREAD

**Issue by arrowcircle** [temporalio/helm-charts#422]
### Is your feature request related to a problem? Please describe.

Latest release of Temporal v1.22 introduced HTTP API on port 7243. Current helm recipe does not support this port and config.

### Describe the solution you'd like

It would be great to have this config available for both service and/or ingress. Service is preferred.

**Comment by robholland** [comment]
The frontend service now exposes the HTTP port as well as GRPC.
