### ISSUE TITLE
[Feature Request] Add ingress for temporal server frontend

### ISSUE THREAD

**Issue by debugger24** [temporalio/helm-charts#430]
### Is your feature request related to a problem? Please describe.

There are scenarios where we need to expose temporal FE with ingress, currently I am adding extending this helm chart to add that support. Would be nice if we can add it.

### Describe the solution you'd like

Add ingress for temporal FE just like web

### Additional context

I can pick this up if we think we should add it.

**Comment by joshbranham** [comment]
Yeah it looks like the `frontend:` only supports `service` right now, which we are using an NLB.

**Comment by debugger24** [comment]
Yes, both FE and Web(UI) has service, we should expose both.

Note: FE != UI

**Comment by joshbranham** [comment]
I would think that is a useful change to add 👌
