### ISSUE TITLE
[Feature Request] Allow to skip database creation

### ISSUE THREAD

**Issue by ascknx** [temporalio/helm-charts#440]
### Is your feature request related to a problem? Please describe.

I want to use an existing database with an user that don't have the permission to create the database.

When running the helm chart I get the following error:
```
Unable to create SQL database.	{"error": "pq: permission denied to create database", "logging-call-at": "handler.go:94"}
```

### Describe the solution you'd like

It would be good to have a flag in the helm chart to switch off the db creation and keep the schema creation active (so setting schema.setup.enabled=false doesnt work for me)

**Comment by debugger24** [comment]
I can pick this up.
