### ISSUE TITLE
[Bug] SQL Schema setup/update does not use TLS

### ISSUE THREAD

**Issue by ascknx** [temporalio/helm-charts#441]
### What are you really trying to do?

I want to use Postgres with TLS by setting `server.config.persistence.default.sql.tls.enabled=true`

### Describe the bug

The activation of TLS is ignored by the schema setup/update job.

**Comment by ascknx** [comment]
there is alread a PR for this: https://github.com/temporalio/helm-charts/pull/411

**Comment by robholland** [comment]
#411 is now merged.
