### ISSUE TITLE
Pods Stuck in CrashLoopBackoff on Fresh Deployment to Fresh Kubernetes Cluster

### ISSUE THREAD

**Issue by marc-wilson** [temporalio/helm-charts#470]
### What are you really trying to do?
Install temporal locally on Docker Desktop w/ Kubernetes enabled

Ran through the steps outlined in the read me:

`helm dependencies update`

then the minimal setup

```
helm install \
    --set server.replicaCount=1 \
    --set cassandra.config.cluster_size=1 \
    --set prometheus.enabled=false \
    --set grafana.enabled=false \
    --set elasticsearch.enabled=false \
    temporaltest . --timeout 15m

```
This results in 4 pods stuck in crashloopbackoff state

```
NAME                                      READY   STATUS             RESTARTS        AGE
temporaltest-admintools-75bfc76c5-w5lf5   1/1     Running            0               23m
temporaltest-frontend-69fc9f6b79-96blk    0/1     CrashLoopBackOff   5 (2m40s ago)   5m44s
temporaltest-history-66f85dd854-c2hnk     0/1     CrashLoopBackOff   9 (42s ago)     23m
temporaltest-matching-85f879f4c4-qlkmz    0/1     CrashLoopBackOff   4 (43s ago)     2m24s
temporaltest-web-776786467b-8m97g         1/1     Running            0               23m
temporaltest-worker-655c7c6467-zjjgm      0/1     CrashLoopBackOff   4 (63s ago)     2m33s

```

### Describe the bug

There seems to be an extra step that is missing from the read me. Looking at the logs for the temporaltest-frontend, I get this error. Seems like I need to configure some sort of data source? I see a cassandra instance running...

> [Fx] RUN supply: stub([]temporal.ServerOption)
> [Fx] RUN provide: go.temporal.io/server/temporal.ServerOptionsProvider()
> [Fx] Error returned: received non-nil error from function "go.temporal.io/server/temporal".ServerOptionsProvider
>  /home/builder/temporal/temporal/fx.go:173:
> config validation error: persistence config: datastore "visibility": must provide config for one and only one datastore: elasticsearch, cassandra, sql or custom store
> [Fx] ERROR  Failed to initialize custom logger: could not build arguments for function "go.uber.org/fx".(*module).constructCustomLogger.func2
>  /go/pkg/mod/go.uber.org/fx@v1.20.0/module.go:251:
> failed to build fxevent.Logger:
> could not build arguments for function "go.temporal.io/server/temporal".glob..func8
>  /home/builder/temporal/temporal/fx.go:1037:
> failed to build log.Logger:
> received non-nil error from function "go.temporal.io/server/temporal".ServerOptionsProvider
>  /home/builder/temporal/temporal/fx.go:173:
> config validation error: persistence config: datastore "visibility": must provide config for one and only one datastore: elasticsearch, cassandra, sql or custom store
> Unable to create server. Error: could not build arguments for function "go.uber.org/fx".(*module).constructCustomLogger.func2 (/go/pkg/mod/go.uber.org/fx@v1.20.0/module.go:251): failed to build fxevent.Logger: could not build arguments for function "go.temporal.io/server/temporal".glob..func8 (/home/builder/temporal/temporal/fx.go:1037): failed to build log.Logger: received non-nil error from function "go.temporal.io/server/temporal".ServerOptionsProvider (/home/builder/temporal/temporal/fx.go:173): config validation error: persistence config: datastore "visibility": must provide config for one and only one datastore: elasticsearch, cassandra, sql or custom store.

<img width="1217" alt="image" src="https://github.com/temporalio/helm-charts/assets/19480392/423bc5e3-244a-4b4e-ae9e-c75ade2c6c72">

### Environment/Versions

- OS and processor: MacOS Sonoma 14.3.1 / M3 Max Chip
- Temporal Version: Current repo release?
- Are you using Docker or Kubernetes or building Temporal from source? Docker Desktop with Kubernetes enabled.

**Comment by marc-wilson** [comment]
Seems to be the same issue as this: https://community.temporal.io/t/errors-while-setting-up-temporal-on-local-environment-using-helm-chart/3088/4

**Comment by myst3k** [comment]
Just ran into this, you can run this to get up and running.

git reset --hard 1e5ac0c442ba45c2a5aead316aebdad3301c6d81

**Comment by marc-wilson** [comment]
> Just ran into this, you can run this to get up and running.
> 
> git reset --hard [1e5ac0c](https://github.com/temporalio/helm-charts/commit/1e5ac0c442ba45c2a5aead316aebdad3301c6d81)

Yea, but that's a workaround and not a solution. Hoping for a real fix.

**Comment by yourbuddyconner** [comment]
Thanks for the tip, this got the chart working for me @myst3k

**Comment by robholland** [comment]
Cassandra is not a valid visibility backend. You will have to enable ES visibility if you are using Cassandra for persistence currently. The chart does not yet support using SQL for visibility if you use Cassandra for persistence. I will file an issue to see if we can get the error message updated so that it does not unhelpfully suggest that you can use cassandra for visibility.

**Comment by s-nilsson** [comment]
Unfortunately the project readme does not provide any such information.

**Comment by myst3k** [comment]
These are the docs on the helm chart, I just want to get up and running quickly with a dev setup. It sounds like it may just need to be updated to reflect the current requirements.

![image](https://github.com/temporalio/helm-charts/assets/323607/f92d6415-897e-49de-be24-9fcb101363a4)

**Comment by robholland** [comment]
Added a PR to clarify.
