### ISSUE TITLE
[Bug] Temporal helm-charts ownership and maintainability

### ISSUE THREAD

**Issue by VLZZZ** [temporalio/helm-charts#482]
### What are you really trying to do?

I'm trying to use Temporal.io Self-hosted solution on top of Kubernetes cluster using the official helm-charts.

### Describe the bug
 
Workaround-based installation of the Temporal.io Self-Hosted via provided Helm chart

### Minimal Reproduction

Try to install Helm chart from scratch to the Kubernetes environment

### Environment/Versions

- OS and processor: M1 Mac
- Temporal Version: 1.22.4 (while Chart.yaml states 1.23.0 🥹)
- Kubernetes

### Additional context

The Helm chart installation flow seems to be quite abandoned and unmaintained from my point of view.  
There are a bunch of issues in the project left without any answers except of workarounds from community members, also I see that people are open to contribute to the project based on the approximate Issue/PR ratio.  

May I kindly ask to clarify if the self-hosted installation via Helm chart is still the way to go if I want to use Temporal?  
Or we need to maintain our own Helm chart?  

Thank you!

**Comment by robholland** [comment]
Please stay tuned, there is work underway on improving self-hosted deployment tools and documentation. Unfortunately I can't give timelines, but I am working on it.
