### ISSUE TITLE
[Bug] Failed to pull image "temporalio/admin-tools:1.24.0"

### ISSUE THREAD

**Issue by CarlosBorroto** [temporalio/helm-charts#491]
### What are you really trying to do?

I'm upgrading to temporal-0.39.0 and `admintools` pods are failing to start because of what looks like a mismatch in docker tags used by the chart and what is present in docker.io.

### Describe the bug

Looking at [docker.io](https://hub.docker.com/r/temporalio/admin-tools/tags), it looks like Temporal is now using tags that look like `v1.24.0-0` instead of `1.24.0`. This is causing all pods to try to pull the incorrect image.

```
│ Events:                                                                                                                                                                                                    │
│   Type     Reason     Age                    From               Message                                                                                                                                    │
│   ----     ------     ----                   ----               -------                                                                                                                                    │
│   Normal   Scheduled  5m38s                  default-scheduler  Successfully assigned temporal/temporal-admintools-647697cfbf-q9ngh to ip-10-164-17-207.ec2.internal                                       │
│   Normal   Pulling    4m4s (x4 over 5m38s)   kubelet            Pulling image "temporalio/admin-tools:1.24.0"                                                                                              │
│   Warning  Failed     4m4s (x4 over 5m38s)   kubelet            Failed to pull image "temporalio/admin-tools:1.24.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/tempora │
│ lio/admin-tools:1.24.0": failed to resolve reference "docker.io/temporalio/admin-tools:1.24.0": docker.io/temporalio/admin-tools:1.24.0: not found                                                         │
│   Warning  Failed     4m4s (x4 over 5m38s)   kubelet            Error: ErrImagePull                                                                                                                        │
│   Warning  Failed     3m49s (x6 over 5m38s)  kubelet            Error: ImagePullBackOff                                                                                                                    │
│   Normal   BackOff    31s (x20 over 5m38s)   kubelet            Back-off pulling image "temporalio/admin-tools:1.24.0"
```

### Minimal Reproduction

Deploy `temporal-0.39.0` helm chart version.

**Comment by CarlosBorroto** [comment]
Also reported [here](https://github.com/temporalio/temporal/issues/6052). It might be the actual bug is in the ci in that repo that should push this tag.

**Comment by CarlosBorroto** [comment]
@alexshtin are you recommending even `.Values.server.image.tag` which defaults to `.Chart.AppVersion` should be always specified? Or, just the extra container images like `.Values.admintools.image.tag` and `.Values.web.image.tag`? I can see why having admintools defaulting to `.Chart.AppVersion` is a bad idea seeing they don't share the same image. However, for the server deployment, I don't see the need to explicitly specify unless you are planning to stop updating `.Chart.AppVersion`.

We will start specifying all 3 tags moving forward, although, I would honestly prefer if the helm charts owners would take on providing good defaults for those. We really have no idea which admintools or web image will be supported by a particular chart version.

**Comment by ascknx** [comment]
With helm chart 0.42.0 the same happened with the temporalio/ui image. This is a really bad user experience. Can you please specify the working versions in the helm chart?
