### ISSUE TITLE
[Bug] temporal-0.42.0 specifies invalid default web.image.tag for temporal/ui 

### ISSUE THREAD

**Issue by ianatha** [temporalio/helm-charts#503]
### What are you really trying to do?

I'm trying to install temporal-0.42.0's minimal install as per the README.

### Describe the bug

helm install fails with "Failed to pull image "temporalio/ui:2.27.10": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/temporalio/ui:2.27.10" [...].

This is caused by the default values:
```
web:
  enabled: true
  replicaCount: 1
  image:
    repository: temporalio/ui
    tag: 2.27.10
```
along with the fact that temporalio/ui:2.27.10 isn't published.

An easy workaround exists (override `web.image.tag`)

### Minimal Reproduction

checkout this repo at tab temporal-0.42.0

```
helm install \
    --set server.replicaCount=1 \
    --set cassandra.config.cluster_size=1 \
    --set elasticsearch.replicas=1 \
    --set prometheus.enabled=false \
    --set grafana.enabled=false \
    temporaltest . --timeout 15m
```

**Comment by robholland** [comment]
This was fixed in 0.43.0. https://github.com/temporalio/helm-charts/commit/1ac58dc5eeb6c341e93c119c11a9342f470713eb
