### ISSUE TITLE
Unable to Deploy the Temporal server in Kubernetes

### ISSUE THREAD

**Issue by tharun-encipherhealth** [temporalio/helm-charts#507]
### What are you really trying to do?
i am trying to deploy the temporal server in kubernetes using this helm-charts repository

### Describe the bug

temporaltest-admintools-5566dd7bf9-2rv6k   1/1     Running            0              15m
temporaltest-cassandra-0                   1/1     Running            0              15m
temporaltest-frontend-7bf7b48c88-gqb9x     0/1     CrashLoopBackOff   7 (99s ago)    15m
temporaltest-history-fd47bd687-bfdg8       0/1     CrashLoopBackOff   7 (117s ago)   15m
temporaltest-matching-58f55cd7d7-86tdl     0/1     CrashLoopBackOff   7 (2m7s ago)   15m
temporaltest-web-557b54f748-hwt5k          1/1     Running            0              15m
temporaltest-worker-f6bc6f844-xnwtd        0/1     CrashLoopBackOff   7 (97s ago)    15m 

The pods are faicng issues to run , when i checked the logs those pods which have CrashLoopBackOff 

Error returned: received non-nil error from function "go.temporal.io/server/temporal".ServerOptionsProvider
	/home/runner/work/docker-builds/docker-builds/temporal/temporal/fx.go:183:
config validation error: persistence config: datastore "visibility": must provide config for one and only one datastore: elasticsearch, cassandra, sql or custom store
[Fx] ERROR		Failed to initialize custom logger: could not build arguments for function "go.uber.org/fx".(*module).constructCustomLogger.func2
	/home/runner/go/pkg/mod/go.uber.org/fx@v1.21.1/module.go:292:
failed to build fxevent.Logger:
could not build arguments for function "go.temporal.io/server/temporal".glob..func8
	/home/runner/work/docker-builds/docker-builds/temporal/temporal/fx.go:1009:
failed to build log.Logger:
received non-nil error from function "go.temporal.io/server/temporal".ServerOptionsProvider
	/home/runner/work/docker-builds/docker-builds/temporal/temporal/fx.go:183:
config validation error: persistence config: datastore "visibility": must provide config for one and only one datastore: elasticsearch, cassandra, sql or custom store
Unable to create server. Error: could not build arguments for function "go.uber.org/fx".(*module).constructCustomLogger.func2 (/home/runner/go/pkg/mod/go.uber.org/fx@v1.21.1/module.go:292): failed to build fxevent.Logger: could not build arguments for function "go.temporal.io/server/temporal".glob..func8 (/home/runner/work/docker-builds/docker-builds/temporal/temporal/fx.go:1009): failed to build log.Logger: received non-nil error from function "go.temporal.io/server/temporal".ServerOptionsProvider (/home/runner/work/docker-builds/docker-builds/temporal/temporal/fx.go:183): config validation error: persistence config: datastore "visibility": must provide config for one and only one datastore: elasticsearch, cassandra, sql or custom store.

### Environment/Versions

- OS and processor: [Mac Book Pro]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?
- Kubernetes

**Comment by robholland** [comment]
Please provide the values file you are using.

**Comment by robholland** [comment]
Closing for now, please re-open with details of your values file so we can help you.
