### ISSUE TITLE
[Feature Request] Publish charts to artifacthub.io

### ISSUE THREAD

**Issue by smktpd** [temporalio/helm-charts#509]
Could you, please, publish charts to artifacthub.io

**Comment by ctriley** [comment]
It looks like they may have published the chart here: https://go.temporal.io/helm-charts
https://github.com/temporalio/helm-charts/pull/457

**Comment by robholland** [comment]
We already publish charts as mentioned by @ctriley

**Comment by smktpd** [comment]
Web page https://go.temporal.io/helm-charts returns 404 for me.
I've opened this ticket about uploading charts specifically to artifacthub.io as it is the default chart registry + has a nice web UI for quick overview.
Are you against publishing to 2 places at once (the way it currently gets published AND to artifacthub.io)?

**Comment by robholland** [comment]
There is no web interface with the way we are publishing the charts, just the ability to install via `helm install --repo ...`. I'm not against publishing to artifacthub, but I don't want to do that right now as the chart is about to under go some changes (like dropping prometheus/grafana for example). Once the chart is settled I'll look at publishing to places other than just our github repo.

**Comment by smktpd** [comment]
> I don't want to do that right now as the chart is about to under go some changes

Honestly, I don't see it as a good reason for not publishing it there: charts are versioned, so as soon as you cut prometheus/grafana away - you just publish them with a new chart version and that's it.

**Comment by robholland** [comment]
That doesn't reduce the support issues or confusion from users when the chart values structure changes, or functionality is added/removed. We currently don't have good ways to communicate these things in our release process (changelog is automated as a flat message right now for example). Once the bigger chart changes are done and we have a process for better communication around changes I'll look at publishing more widely.

**Comment by smktpd** [comment]
Got it. Thank you!

**Comment by smktpd** [comment]
Oh, by the way, (I am sorry to ask it in this ticket, but this github project doesn't have 'discussions' tab enabled) now that you shared some plans about upcoming structural changes of the chart - could you, please, share your vision about including templates for `kind: ExternalSecret` (which are CRDs provided by [External Secrets Operator](https://github.com/external-secrets/external-secrets))?
Currently I have to HEAVILY patch your chart to make it work with secrets getting brought from Vault via ExternalSecrets and that's so painful right now, as the currently scripted chart's logic conflicts with it quite a lot.

**Comment by robholland** [comment]
Discussions should now be enabled... Please start one! :)
