### ISSUE TITLE
[Feature Request] Remove dependency on Grafana

### ISSUE THREAD

**Issue by BrianKopp** [temporalio/helm-charts#518]
### Is your feature request related to a problem? Please describe.

Monitoring tools shouldn't be specified by this application.

### Describe the solution you'd like

Remove dependencies on monitoring tools.

**Comment by robholland** [comment]
I would add that we should continue to add Prometheus annotations though if `prometheus.enable` is true. Or, maybe a new value with a more intent-revealing name that toggles the annotations.

**Comment by BrianKopp** [comment]
Ok sounds good. I'll split these up into two different PRs, the first for grafana, the second for prometheus. The grafana removal is much more straightforward. There are some different choices that could be made on the prometheus side of things for implementing scrape config (labels, servicemonitors, etc.), as well as where to draw the line for what stays in.

**Comment by BrianKopp** [comment]
Moving Prometheus discussion to #527
