### ISSUE TITLE
[Bug] `helm upgrade` does not work if `schema.enabled` is true

### ISSUE THREAD

**Issue by kosmoz** [temporalio/helm-charts#554]
### What are you really trying to do?

Running `helm upgrade` on an existing release of the temporal chart.

### Describe the bug

Schema migrations are performed in a `Job`, but the resource is never garbage collected. When trying to upgrade the release, helm fails because the `Job` resource has immutable fields.

### Minimal Reproduction
1. Install helm chart
2. Try to upgrade helm release

### Environment/Versions

- Temporal Version: helm chart 0.45.0

**Comment by kosmoz** [comment]
Can be fixed by setting the `ttlSecondsAfterFinished` on the Job. I will create a PR shortly.

**Comment by FurqanHabibi** [comment]
Another alternative is to specify the job as a `pre-install` [hook](https://helm.sh/docs/topics/charts_hooks/#the-available-hooks). Will create a PR for this approach.

**Comment by robholland** [comment]
Please give https://github.com/temporalio/helm-charts/pull/564 a try.

**Comment by robholland** [comment]
Please re-open if this is still broken.
