### ISSUE TITLE
create "default" namespace by default

### ISSUE THREAD

**Issue by markmark206** [temporalio/helm-charts#56]
When running the system via `docker-compose` (e. g. https://github.com/temporalio/temporal/blob/master/docker/docker-compose.yml), the system starts up with `default` namespace already existing. However, this is not the case when deploying the system via helm chart.

Please add default namespace when deploying temporal via helm chart.

PS Thanks to Remy for reporting this!

**Comment by tgaddair** [comment]
Hey @markmark206 any update on this? Is there a good workaround when doing an automated deployment that doesn't require calling `tctl` by hand?

**Comment by underrun** [comment]
we've come to the conclusion that for our helm charts we should not create a default namespace by default because having a default namespace is only a convenience for development - which is why it's automatically created when running temporal via docker-compose.

additionally since namespaces cannot currently be deleted we would be adding something that is more likely to cause accidental problems in production environments but that has no way of being removed (as is still an issue with kubernetes default namespaces and one we'd like to avoid if we can).

**Comment by siddharthwe360** [comment]
I have a related question. Even if the default namespace is not created automatically, should the helm chart not have a way to configure some pre-created namespaces via the values ?

**Comment by vinodnaidu02** [comment]
Any update or a workaround on this issue ?

**Comment by YannickZ** [comment]
agreed, even though this shouldn't be a the default behaviour there should be a parameter available on the helmchart to do it

**Comment by alex-derzhi-sp** [comment]
Would you all accept a PR to fix this?

**Comment by robholland** [comment]
#420 opened to track this. PRs accepted.

**Comment by gshanemiller** [comment]
And make sure the default namespace is created for those self-hosting. After fighting TLS configuration getting temporal-server and ui-server up and running, the first thing I see in the web-UI is "An Error Occurred Namespace default is not found" even though the doc says it's automatically created.

In  the meanwhile I suppose I will work around this through GO client code.

I might also point the out the following. Temporal represents it supports cloud offerings, self-hosted, plus a third Temporal-CLI option. That's three places to make sure this is fixed. Other than a good sales/marketing story of getting something trivial up and running fast, who really runs dockerized apps at scale? Maybe consider dropping the docker Temporal-CLI and cleanup self-hosting keeping Cloud as an another excellent option. That is running through Docker doesn't move the needle on cloud or self-hosted setup+config.
