### ISSUE TITLE
[Feature Request] Ability to specify SQL_CONNECT_ATTRIBUTES for temporal-schema job

### ISSUE THREAD

**Issue by adigiorgi-clickup** [temporalio/helm-charts#561]
### Is your feature request related to a problem? Please describe.
The `temporal-schema` job always tries to create tables in the `public` schema, but our DBAs don't allow the use of the `public` schema.

By setting the `SQL_CONNECT_ATTRIBUTES` env var to something like `search_path=temporalvisibility`, we can actually tell `temporal-schema` to populate a different schema, but unfortunately the Helm chart doesn't allow to specify `SQL_CONNECT_ATTRIBUTES`.

### Describe the solution you'd like
Allow to specify the `SQL_CONNECT_ATTRIBUTES` env var for the `temporal-schema` job in the Helm chart.

### Additional context
N/A

**Comment by adigiorgi-clickup** [comment]
If you like the idea, I'd be happy to try and send a PR!

**Comment by robholland** [comment]
Hey, yes I'd be interested in a PR for this.
