### ISSUE TITLE
README: Document running over mysql, without Elastic Search

### ISSUE THREAD

**Issue by markmark206** [temporalio/helm-charts#57]
The current README doesn't make it super-clear how to install temporal without ElasticSearch/extended Visibility features.

Here is a thread that describes this setup:

https://community.temporal.io/t/running-visibility-on-my-sql-in-k8s-setup/369?u=markmark

Please update the README to explicitly call out this scenario.

**Comment by sw-yx** [comment]
we'll be working on a slimmed down version now, thank you.
