### ISSUE TITLE
[Bug] server-pdb is broken

### ISSUE THREAD

**Issue by FurqanHabibi** [temporalio/helm-charts#572]
### What are you really trying to do?

Deploy temporal with pdb.

### Describe the bug

server-pdb is broken and can't be deployed because it uses `.` inside range block
https://github.com/temporalio/helm-charts/blob/main/charts/temporal/templates/server-pdb.yaml#L10

Instead it should use `$`.

### Minimal Reproduction

Try to deploy temporal with pdb
```
helm install \
    --repo https://go.temporal.io/helm-charts \
    --set server.frontend.replicaCount=2 \
    --set server.frontend.podDisruptionBudget.minAvailable=1 \
    temporaltest temporal \
    --timeout 15m
```

### Environment/Versions

- OS and processor: Linux
- Temporal Version: 1.25.0
- Kubernetes 1.30

**Comment by robholland** [comment]
Fixed in #568.
