### ISSUE TITLE
[Bug]  Helm chart version 0.38.1 fails to install due to temporalio/admin-tools:1.23.1 is missing on DockerHub

### ISSUE THREAD

**Issue by rodionovilya** [temporalio/helm-charts#594]
**What are you really trying to do?**
I am trying to install Temporal using the Helm chart version 0.38.1, which is supposed to install Temporal version 1.23.1. The goal is to have both the Temporal services and the Temporal admin tools installed. However, the installation process fails because the Docker image tag 1.23.1 for the admin tools is no longer available on DockerHub.

**Describe the bug**
When attempting to install Temporal version 1.23.1 using Helm chart version 0.38.1, the installation of the Temporal admin tools fails due to the absence of the 1.23.1 tag for the admin tools on DockerHub. Temporal services are installed successfully, but the missing Docker image tag prevents the admin tools from being deployed.

**Error log:**

Error: failed to pull image "temporalio/admin-tools:1.23.1" - tag not found

**Minimal Reproduction**
To reproduce the issue:

Install the Temporal Helm chart version 0.38.1 with the following command:
helm install temporalio/temporal --version 0.38.1
Observe that Temporal services install successfully, but the admin tools fail to deploy due to the missing Docker image tag for version 1.23.1.

**Environment/Versions**
OS and processor: (e.g., Ubuntu 20.04, x86)
Temporal Version: 1.23.1 (Helm chart version 0.38.1)
Deployment environment: Kubernetes using Helm for installation

**Additional context**
This issue appears to be caused by the removal of the 1.23.1 tag from DockerHub for Temporal's admin tools. A potential workaround may be to manually specify an available version of the admin tools in the Helm values or pull a different Docker image tag.

**Comment by robholland** [comment]
Newer versions are working as intended.
