### ISSUE TITLE
[Bug] Incorrect Reference to a Helm Value Causing a Nil Pointer Error

### ISSUE THREAD

**Issue by nzuguem** [temporalio/helm-charts#616]
### What are you really trying to do?

I am trying to install version `0.53.0` of the Helm chart.

### Describe the bug

When I install version `0.53.0` of the Helm chart, I get this error:

```
Error: template: temporal/templates/server-job.yaml:148:40: executing "temporal/templates/server-job.yaml" at <.Values.server>: nil pointer evaluating interface {}.server
```

Upon investigation, I found that in the Helm chart (`temporal/templates/server-job.yaml:148:40`), there is an attempt to access a global object (`server`) from the local scope (in this case, within a `range`), using the local context expression `.Values.server`. However, in our case (due to the local scope change within the `range`), `.Values.server` no longer behaves as expected, because the context has been altered by Helm.

### Minimal Reproduction

Install version `0.53.0` of the Helm chart with **namespace creation enabled** :

```bash
helm upgrade --install temporal-release temporal --repo https://go.temporal.io/helm-charts  --version 0.53.0 --set server.config.namespaces.create=true

# Error: template: temporal/templates/server-job.yaml:148:40: executing "temporal/templates/server-job.yaml" at <.Values.server>: nil pointer evaluating interface {}.server
```

### Environment/Versions

- Kind Version : kind v0.26.0 go1.23.4 darwin/arm64
- Kubernetes Server Version : v1.32.0
- Helm Version : v3.15.3
- Temporal Helm Chart Version: 0.53.0

**Comment by tomwheeler** [comment]
I have reproduced the problem and confirmed this this PR resolves it. Thank you for your contribution, @nzuguem!
