### ISSUE TITLE
Archival feature is not being set to Enabled

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/helm-charts#64]
Necessary changes that should enable archival on cluster level https://github.com/temporalio/helm-charts/pull/63
There is still something missing in the PR

Repro:
1. Install temporal service
``` bash
helm install temporaltest . --timeout 900s
```
2. Create a namespace with archivals enabled
``` bash
kubectl exec -it services/temporaltest-admintools -- bash -c "tctl --ns nstest n register -has enabled -vas enabled"
```
3. Check whether archival status is enabled
``` bash
kubectl exec -it services/temporaltest-admintools -- bash -c "tctl --ns nstest namespace describe""
```

Expected:
Archivals are enabled
Actual:
Archivals are disabled

**Comment by MrSaints** [comment]
It'd be great if we can set the archival configuration through Helm values, rather than hardcoding.

And for it to be useful, I believe we also need a way to pass in additional environment variables (to support S3 for example).

**Comment by sw-yx** [comment]
agreed and taking note for @tsurdilo revamp
